version: "3.8"

services:
  minecraft-server:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: mc-server
    ports:
      - "25565:25565"           
      - "25575:25575"
    volumes:
      - ./data:/server         
    stdin_open: true           
    tty: true                  
    restart: always            

  
